### ISSUE TITLE
portable data?

### ISSUE THREAD

**Issue by crimsonduelist** [Jelmerro/crossdirstat#8]
Is there a flag I can pass so that it uses custom folder location instead of %appdata%/Crossdirstat for example on windows

**Comment by Jelmerro** [comment]
Since all crossdirstat data is temporary Electron data, I'll probably move the data to the temp folder in a future release. Would this be sufficient, or would you like a custom location to be possible? Keep in mind that none of this data is important (as in, needs to be persistent) for running crossdirstat.

**Comment by crimsonduelist** [comment]
yes that would be enough then thank u.

**Comment by Jelmerro** [comment]
fixed in [2.3.0](https://github.com/Jelmerro/crossdirstat/releases/tag/2.3.0) :)
